spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        
        - id: discovery-server
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        
        - id: discovery-server-static
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: api-gateway