eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}

spring:
  cloud:
    config:
      uri: http://config-server:8888